//! Compiles `/proto` into Rust with prost-build. protox parses the files, so no `protoc` has to be
//! installed.
//!
//! Messages with a `[(api.v1.secret) = true]` field get a hand-rolled `Debug` that prints
//! `<redacted>` in place of it; the rest derive `Debug` as usual.

use std::{
    env,
    error::Error,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use prost_reflect::{DescriptorPool, MessageDescriptor};

const PACKAGE: &str = "api.v1";
const SECRET_OPTION: &str = "api.v1.secret";

const PROTO_DIR: &str = "../../../proto";

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join(PROTO_DIR);
    let root = root
        .canonicalize()
        .map_err(|err| format!("the .proto files are expected in {}: {err}", root.display()))?;

    let mut files = Vec::new();
    collect_protos(&root, &mut files)?;
    files.sort();
    // Relative to the package, not absolute: Cargo then tracks this checkout's files even when
    // several checkouts share a `CARGO_TARGET_DIR`. The directory catches added files, each file an
    // edit.
    println!("cargo:rerun-if-changed={PROTO_DIR}");
    for file in &files {
        let relative = Path::new(PROTO_DIR).join(file.strip_prefix(&root)?);
        println!("cargo:rerun-if-changed={}", relative.display());
    }

    let mut compiler = protox::Compiler::new([&root])?;
    compiler.include_source_info(true).include_imports(true);
    compiler.open_files(&files)?;

    let pool = compiler.descriptor_pool();
    let redacted = redacted_messages(&pool)?;

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let mut config = prost_build::Config::new();
    config.skip_debug(
        redacted
            .iter()
            .map(|message| format!(".{}", message.full_name())),
    );
    config.compile_fds(compiler.file_descriptor_set())?;

    fs::write(out_dir.join("redacted.rs"), debug_impls(&pool, &redacted)?)?;
    Ok(())
}

fn collect_protos(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_protos(&path, files)?;
        } else if path.extension().is_some_and(|ext| ext == "proto") {
            files.push(path);
        }
    }
    Ok(())
}

fn redacted_messages(pool: &DescriptorPool) -> Result<Vec<MessageDescriptor>, Box<dyn Error>> {
    let secret = pool
        .get_extension_by_name(SECRET_OPTION)
        .ok_or("the `api.v1.secret` option is not defined (proto/api/v1/options.proto)")?;
    let is_secret = |field: &prost_reflect::FieldDescriptor| {
        field.options().get_extension(&secret).as_bool() == Some(true)
    };

    let mut redacted = Vec::new();
    for message in pool.all_messages() {
        if message.package_name() != PACKAGE || !message.fields().any(|field| is_secret(&field)) {
            continue;
        }
        if message.parent_message().is_some() {
            return Err(format!(
                "{}: secret fields are only supported in top-level messages",
                message.full_name()
            )
            .into());
        }
        for field in message.fields().filter(|field| is_secret(field)) {
            let in_oneof = field
                .containing_oneof()
                .is_some_and(|oneof| !oneof.is_synthetic());
            if in_oneof {
                return Err(format!(
                    "{}: a secret field cannot be part of a oneof",
                    field.full_name()
                )
                .into());
            }
        }
        redacted.push(message);
    }
    Ok(redacted)
}

fn debug_impls(
    pool: &DescriptorPool,
    messages: &[MessageDescriptor],
) -> Result<String, Box<dyn Error>> {
    let secret = pool
        .get_extension_by_name(SECRET_OPTION)
        .ok_or("the `api.v1.secret` option is not defined")?;

    let mut out = String::from("// Generated by build.rs: `Debug` for messages with secrets.\n");
    for message in messages {
        let name = message.name();
        writeln!(out, "impl ::core::fmt::Debug for {name} {{")?;
        writeln!(
            out,
            "    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {{"
        )?;
        writeln!(out, "        f.debug_struct({name:?})")?;
        let mut oneofs = Vec::new();
        for field in message.fields() {
            if let Some(oneof) = field
                .containing_oneof()
                .filter(|oneof| !oneof.is_synthetic())
            {
                // prost holds a oneof in one field named after it.
                if !oneofs.contains(&oneof.name().to_owned()) {
                    oneofs.push(oneof.name().to_owned());
                    let ident = rust_ident(oneof.name())?;
                    writeln!(out, "            .field({:?}, &self.{ident})", oneof.name())?;
                }
                continue;
            }
            let ident = rust_ident(field.name())?;
            if field.options().get_extension(&secret).as_bool() == Some(true) {
                writeln!(
                    out,
                    "            .field({:?}, &::core::format_args!(\"<redacted>\"))",
                    field.name()
                )?;
            } else {
                writeln!(out, "            .field({:?}, &self.{ident})", field.name())?;
            }
        }
        writeln!(out, "            .finish()")?;
        writeln!(out, "    }}")?;
        writeln!(out, "}}")?;
    }
    Ok(out)
}

/// The field prost generates for `name`. Our names are already snake case, so only Rust keywords
/// would differ; those are refused rather than second-guessed.
fn rust_ident(name: &str) -> Result<&str, Box<dyn Error>> {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "box", "break", "const", "continue", "crate", "dyn", "else",
        "enum", "extern", "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match",
        "mod", "move", "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait",
        "true", "try", "type", "unsafe", "use", "where", "while", "yield",
    ];
    if KEYWORDS.contains(&name) || name.chars().any(char::is_uppercase) {
        return Err(format!("rename the field `{name}` in a message with secrets").into());
    }
    Ok(name)
}
