create table users (
    -- UUIDv7, generated by the application: time-ordered, so `order by id` is creation order.
    id uuid primary key,
    email text not null check (char_length(email) between 3 and 254),
    -- Lowercased by the application; 3-30 of a-z 0-9 . _ - with at least one letter.
    username text not null check (username ~ '^[a-z0-9][a-z0-9._-]{2,29}$' and username ~ '[a-z]'),
    -- An Argon2id PHC string, never the password itself.
    password_hash text not null,
    email_verified_at timestamptz,
    -- Set while the account is disabled; disabled accounts cannot sign in.
    disabled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Emails are unique regardless of case. The application already stores them lowercased;
-- the index also covers rows written any other way, and serves lookups by email.
create unique index users_email_lower_key on users (lower(email));
create unique index users_username_lower_key on users (lower(username));

create trigger users_set_updated_at before update on users
    for each row execute function set_updated_at();
